// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv1s6MHdwveeYs36kn1Qdxw-qMj53j3DE',
    appId: '1:1055198663265:web:0e41b538502fb73341d020',
    messagingSenderId: '1055198663265',
    projectId: 'trai-studio',
    authDomain: 'trai-studio.firebaseapp.com',
    storageBucket: 'trai-studio.appspot.com',
    measurementId: 'G-ZSY25MC1PP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB7UyImIE2_DSY5s-TMr0dMXZT9bv6HUw',
    appId: '1:1055198663265:android:267c6ee10f6e8aee41d020',
    messagingSenderId: '1055198663265',
    projectId: 'trai-studio',
    storageBucket: 'trai-studio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX1tWc57p-_p6wvLBnQxk1kwr-OPSFOcw',
    appId: '1:1055198663265:ios:ccab3c6a5d50e3d041d020',
    messagingSenderId: '1055198663265',
    projectId: 'trai-studio',
    storageBucket: 'trai-studio.appspot.com',
    androidClientId: '1055198663265-cj2tsqrmf5casdamlsi7patuivo3915q.apps.googleusercontent.com',
    iosClientId: '1055198663265-cd867opqnm65dl8t56vf6e3keihhkjvm.apps.googleusercontent.com',
    iosBundleId: 'app.trai.traistudio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX1tWc57p-_p6wvLBnQxk1kwr-OPSFOcw',
    appId: '1:1055198663265:ios:ccab3c6a5d50e3d041d020',
    messagingSenderId: '1055198663265',
    projectId: 'trai-studio',
    storageBucket: 'trai-studio.appspot.com',
    androidClientId: '1055198663265-cj2tsqrmf5casdamlsi7patuivo3915q.apps.googleusercontent.com',
    iosClientId: '1055198663265-cd867opqnm65dl8t56vf6e3keihhkjvm.apps.googleusercontent.com',
    iosBundleId: 'app.trai.traistudio',
  );
}
